server:
  port: 8097
spring:
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # OSIV 설정 끄기

management:
  endpoints:
    web:
      exposure:
        include: health  # 이 부분 추가

springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로
  api-docs:
    path: /api-docs        # API 문서 경로

services:
  auth:
    url: http://43.203.126.129:8090  # 인증 서비스 URL
  noti:
    url: http://43.203.126.129:8097  # 인증 서비스 URL

custom:
  prod:
    cookieDomain: pawpaw.kknaks.site
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    name: "pawpaw"
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"
