server:
  port: 8091
spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: dev
    include: secret
  kafka:
    bootstrap-servers: 43.203.126.129:19092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.ll.hereispaw.domain.noti.dto.kafka
        spring.json.use.type.headers: false
logging:
  level:
    root: info
    com.ll.hereispaw : debug
    org.hibernate.spatial: debug
springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로
  api-docs:
    path: /api-docs        # API 문서 경로
custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:5173"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: pawpaw.kknaks.site
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    name: "PawPaw"
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
